const editorActionTypes = {
  CONTENT_CHANGED: 'CONTENT_CHANGED',
  FETCH_EDITOR_CONTENT: 'FETCH_EDITOR_CONTENT',
  FETCH_EDITOR_CONTENT_SUCCESS: 'FETCH_EDITOR_CONTENT_SUCCESS',
  FETCH_EDITOR_CONTENT_FAILED: 'FETCH_EDITOR_CONTENT_FAILED',
};

export default editorActionTypes;
