const editorActionTypes = {
  CONTENT_CHANGED: 'CONTENT_CHANGED',
  NEW_EDITOR_CONTENT: 'NEW_EDITOR_CONTENT',
  FETCH_EDITOR_CONTENT: 'FETCH_EDITOR_CONTENT',
  FETCH_EDITOR_CONTENT_SUCCESS: 'FETCH_EDITOR_CONTENT_SUCCESS',
  FETCH_EDITOR_CONTENT_FAILURE: 'FETCH_EDITOR_CONTENT_FAILURE',
  REMOVING_NOTE: 'REMOVING_NOTE',
  REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
  REMOVE_NOTE_FAILURE: 'REMOVE_NOTE_FAILURE',
};

export default editorActionTypes;
