const editorActionTypes = {
  CONTENT_CHANGED: 'CONTENT_CHANGED',
  FETCH_EDITOR_CONTENT: 'FETCH_EDITOR_CONTENT',
  FETCH_EDITOR_CONTENT_SUCCESS: 'FETCH_EDITOR_CONTENT_SUCCESS',
  FETCH_EDITOR_CONTENT_FAILED: 'FETCH_EDITOR_CONTENT_FAILED',
  REMOVING_NOTE: 'REMOVING_NOTE',
  REMOVE_NOTE_SUCCESS: 'REMOVE_NOTE_SUCCESS',
};

export default editorActionTypes;
